import type { RoleKnowledgeProfile } from "./role-intelligence-schemas";

const emptyProfileFields: Pick<RoleKnowledgeProfile, "workEnvironments" | "competencies" | "safetyConstraints"> = {
  workEnvironments: [],
  competencies: [],
  safetyConstraints: [],
};

/**
 * Small evaluation corpus for the role-intelligence foundation. These are
 * not a substitute for O*NET/ESCO ingestion; they are source-mapped fixtures
 * that make the expected retrieval behavior deterministic before runtime is
 * connected to the new database tables.
 */
export const ROLE_INTELLIGENCE_FIXTURES: RoleKnowledgeProfile[] = [
  {
    ...emptyProfileFields,
    id: "erp-implementation-assistant",
    kind: "internship_overlay",
    canonicalTitle: "ERP Implementation Assistant",
    internshipTitle: "ERP Implementation Assistant Intern",
    alternateTitles: ["ERP Implementation Intern", "ERP Migration Intern", "ERP Support Intern"],
    occupationFamily: "Computer and Information Systems",
    description: "Supports enterprise-system implementation and data migration preparation, testing, validation, and documentation.",
    typicalTasks: ["Clean and prepare source data for migration", "Map source fields to target ERP fields", "Validate transformed records", "Document migration issues", "Support user acceptance testing"],
    workActivities: ["ERP implementation support", "Data migration", "Data cleansing", "Data mapping", "Migration validation", "Transition support"],
    skills: ["Data quality", "Requirements documentation", "Testing", "Process documentation"],
    knowledge: ["Enterprise resource planning systems", "Systems implementation", "Data migration"],
    commonTools: ["SAP", "Oracle ERP", "Microsoft Dynamics"],
    typicalDeliverables: ["Clean migration dataset", "Field mapping document", "Migration validation report", "Issue log"],
    sourceMappings: [
      { source: "onet", externalId: "15-1211.00", relation: "narrower", sourceVersion: "31.0" },
      { source: "internin_curated", externalId: "erp-implementation-assistant-v1", relation: "exact", sourceVersion: "1" },
    ],
  },
  {
    ...emptyProfileFields,
    id: "financial-systems-analyst",
    kind: "internship_overlay",
    canonicalTitle: "Financial Systems Analyst",
    internshipTitle: "Financial Systems Analyst Intern",
    alternateTitles: ["Finance Systems Intern"],
    occupationFamily: "Accounting and Information Systems",
    description: "Supports analysis and reporting across financial systems and financial datasets.",
    typicalTasks: ["Analyze financial-system data", "Prepare financial reports", "Investigate reporting discrepancies", "Document finance-system requirements"],
    workActivities: ["Financial systems analysis", "Financial reporting", "Data reconciliation", "Requirements analysis"],
    skills: ["Financial analysis", "Data analysis", "Reconciliation", "Reporting"],
    knowledge: ["Accounting", "Financial reporting systems"],
    commonTools: ["SAP", "Oracle Financials", "Excel"],
    typicalDeliverables: ["Financial systems report", "Reconciliation workbook", "Requirements summary"],
    sourceMappings: [{ source: "internin_curated", externalId: "financial-systems-analyst-v1", relation: "exact", sourceVersion: "1" }],
  },
  {
    ...emptyProfileFields,
    id: "business-operations",
    kind: "internship_overlay",
    canonicalTitle: "Business Operations",
    internshipTitle: "Business Operations Intern",
    alternateTitles: ["Operations Intern"],
    occupationFamily: "Business Operations",
    description: "Supports recurring operational processes, coordination, documentation, and performance tracking.",
    typicalTasks: ["Document operational processes", "Track operational metrics", "Coordinate recurring workflows", "Identify process bottlenecks"],
    workActivities: ["Operations coordination", "Process documentation", "Performance tracking", "Process improvement"],
    skills: ["Organization", "Documentation", "Spreadsheet analysis"],
    knowledge: ["Business operations"],
    commonTools: ["Excel", "Project management software"],
    typicalDeliverables: ["Process map", "Operations tracker", "Improvement memo"],
    sourceMappings: [{ source: "internin_curated", externalId: "business-operations-v1", relation: "exact", sourceVersion: "1" }],
  },
  {
    ...emptyProfileFields,
    id: "it-support",
    kind: "internship_overlay",
    canonicalTitle: "IT Support Specialist",
    internshipTitle: "IT Support Intern",
    alternateTitles: ["Help Desk Intern", "IT Technician Intern"],
    occupationFamily: "Information Technology Support",
    description: "Diagnoses and resolves common user hardware, software, printer, account, and device issues.",
    typicalTasks: ["Troubleshoot employee laptops", "Resolve printer issues", "Fix common software problems", "Document support tickets"],
    workActivities: ["User technical support", "Hardware troubleshooting", "Software troubleshooting", "Device setup"],
    skills: ["Troubleshooting", "Customer support", "Technical documentation"],
    knowledge: ["Computer hardware", "Operating systems"],
    commonTools: ["Windows", "macOS", "Microsoft 365", "Ticketing system"],
    typicalDeliverables: ["Resolved ticket", "Troubleshooting notes", "Device setup checklist"],
    sourceMappings: [{ source: "onet", externalId: "15-1232.00", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "data-reporting-analyst",
    kind: "internship_overlay",
    canonicalTitle: "Data Reporting Analyst",
    internshipTitle: "Data Reporting Analyst Intern",
    alternateTitles: ["Reporting Analyst Intern", "Business Intelligence Intern"],
    occupationFamily: "Data and Business Intelligence",
    description: "Cleans recurring datasets and turns them into accurate reports and dashboards.",
    typicalTasks: ["Clean spreadsheet data", "Build weekly dashboards", "Validate report totals", "Automate recurring reports"],
    workActivities: ["Data cleaning", "Dashboard creation", "Reporting", "Data validation"],
    skills: ["Spreadsheet analysis", "Data visualization", "Reporting"],
    knowledge: ["Data quality", "Business intelligence"],
    commonTools: ["Excel", "Google Sheets", "Power BI", "Tableau"],
    typicalDeliverables: ["Clean dataset", "Weekly dashboard", "Data quality notes"],
    sourceMappings: [{ source: "onet", externalId: "15-2051.01", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "graphic-designer",
    kind: "internship_overlay",
    canonicalTitle: "Graphic Designer",
    internshipTitle: "Graphic Design Intern",
    alternateTitles: ["Visual Design Intern", "Graphic Designer Intern"],
    occupationFamily: "Design and Creative",
    description: "Creates visual assets and layouts that communicate information clearly through typography, imagery, and composition.",
    typicalTasks: ["Create visual assets", "Design marketing layouts", "Prepare brand-aligned graphics", "Revise designs from feedback"],
    workActivities: ["Graphic design", "Visual communication", "Layout design", "Image editing"],
    skills: ["Graphic design", "Typography", "Visual composition"],
    knowledge: ["Design principles", "Brand systems"],
    commonTools: ["Adobe Illustrator", "Adobe Photoshop", "Figma"],
    typicalDeliverables: ["Design mockup", "Visual asset set", "Export-ready graphics"],
    sourceMappings: [{ source: "onet", externalId: "27-1024.00", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "backend-developer",
    kind: "internship_overlay",
    canonicalTitle: "Backend Developer",
    internshipTitle: "Backend Developer Intern",
    alternateTitles: ["Back-End Developer Intern", "API Developer Intern"],
    occupationFamily: "Software Development",
    description: "Builds server-side application logic, APIs, data access, and automated tests.",
    typicalTasks: ["Build backend APIs", "Implement server-side application logic", "Connect services to databases", "Test API behavior"],
    workActivities: ["Backend development", "API development", "Database integration", "Server-side testing"],
    skills: ["Programming", "API design", "Database access"],
    knowledge: ["Software development", "Web services"],
    commonTools: ["Node.js", "REST APIs", "PostgreSQL", "TypeScript"],
    typicalDeliverables: ["API endpoint", "Automated tests", "Pull request"],
    sourceMappings: [{ source: "onet", externalId: "15-1252.00", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "frontend-developer",
    kind: "internship_overlay",
    canonicalTitle: "Front-End Developer",
    internshipTitle: "Frontend Developer Intern",
    alternateTitles: ["Front-End Intern", "Web UI Developer Intern"],
    occupationFamily: "Software Development",
    description: "Builds browser interfaces and connects them to application programming interfaces.",
    typicalTasks: ["Build React interfaces", "Connect user interfaces to APIs", "Implement responsive layouts", "Fix frontend bugs"],
    workActivities: ["Frontend development", "User interface development", "API integration", "Web accessibility"],
    skills: ["JavaScript", "TypeScript", "HTML", "CSS"],
    knowledge: ["Web development", "Browser applications"],
    commonTools: ["React", "TypeScript", "HTML/CSS", "REST APIs"],
    typicalDeliverables: ["Working interface", "API-connected screen", "Pull request"],
    sourceMappings: [{ source: "onet", externalId: "15-1254.00", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "full-stack-developer",
    kind: "internship_overlay",
    canonicalTitle: "Full Stack Developer",
    internshipTitle: "Full Stack Developer Intern",
    alternateTitles: ["Full-Stack Intern"],
    occupationFamily: "Software Development",
    description: "Builds application interfaces, backend services, and the connections between them.",
    typicalTasks: ["Build frontend interfaces", "Develop backend APIs", "Connect interfaces to APIs", "Work with application databases"],
    workActivities: ["Frontend development", "Backend development", "API development", "Database integration"],
    skills: ["JavaScript", "TypeScript", "Server-side development"],
    knowledge: ["Web applications", "Software development"],
    commonTools: ["React", "Node.js", "TypeScript", "REST APIs", "PostgreSQL"],
    typicalDeliverables: ["Working full-stack feature", "API endpoint", "Pull request"],
    sourceMappings: [{ source: "onet", externalId: "15-1254.00", relation: "related", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "accounting-finance",
    kind: "internship_overlay",
    canonicalTitle: "Accounting Assistant",
    internshipTitle: "Accounting Intern",
    alternateTitles: ["Finance and Accounting Intern", "Junior Accounting Intern"],
    occupationFamily: "Accounting and Finance",
    description: "Supports invoice reconciliation, ledger accuracy, month-end reporting, and finance documentation.",
    typicalTasks: ["Reconcile invoices", "Prepare monthly financial reports", "Check ledger entries", "Investigate payment discrepancies"],
    workActivities: ["Account reconciliation", "Invoice processing", "Financial reporting", "Bookkeeping"],
    skills: ["Accounting", "Reconciliation", "Spreadsheet accuracy"],
    knowledge: ["Financial statements", "Bookkeeping"],
    commonTools: ["Excel", "QuickBooks", "Xero"],
    typicalDeliverables: ["Reconciliation workbook", "Monthly financial report", "Exception log"],
    sourceMappings: [{ source: "onet", externalId: "13-2011.00", relation: "narrower", sourceVersion: "31.0" }],
  },
  {
    ...emptyProfileFields,
    id: "crm-administration",
    kind: "internship_overlay",
    canonicalTitle: "CRM Administrator",
    internshipTitle: "CRM Administration Intern",
    alternateTitles: ["CRM Support Intern"],
    occupationFamily: "Business Systems Administration",
    description: "Maintains CRM configuration, fields, permissions, records, and user support.",
    typicalTasks: ["Configure CRM fields", "Manage CRM users", "Maintain CRM records", "Document CRM processes"],
    workActivities: ["CRM configuration", "CRM administration", "User support"],
    skills: ["Systems administration", "Data quality"],
    knowledge: ["Customer relationship management systems"],
    commonTools: ["CRM", "Salesforce", "HubSpot"],
    typicalDeliverables: ["CRM configuration", "Data quality report", "User guide"],
    sourceMappings: [{ source: "internin_curated", externalId: "crm-administration-v1", relation: "exact", sourceVersion: "1" }],
  },
  {
    ...emptyProfileFields,
    id: "sales-operations",
    kind: "internship_overlay",
    canonicalTitle: "Sales Operations Analyst",
    internshipTitle: "Sales Operations Intern",
    alternateTitles: ["Revenue Operations Intern"],
    occupationFamily: "Sales Operations",
    description: "Analyzes pipeline data, prepares sales reports, and supports sales-process operations.",
    typicalTasks: ["Analyze CRM pipeline data", "Prepare sales reports", "Clean sales records", "Track sales metrics"],
    workActivities: ["Sales data analysis", "Pipeline reporting", "Sales process support"],
    skills: ["Reporting", "Data analysis"],
    knowledge: ["Sales operations"],
    commonTools: ["CRM", "Salesforce", "Excel"],
    typicalDeliverables: ["Pipeline report", "Sales dashboard", "Data cleanup log"],
    sourceMappings: [{ source: "internin_curated", externalId: "sales-operations-v1", relation: "exact", sourceVersion: "1" }],
  },
  {
    ...emptyProfileFields,
    id: "crm-integration-developer",
    kind: "internship_overlay",
    canonicalTitle: "CRM Integration Developer",
    internshipTitle: "CRM Integration Developer Intern",
    alternateTitles: ["CRM Developer Intern"],
    occupationFamily: "Software Integration",
    description: "Builds and tests integrations between CRM platforms and other business applications.",
    typicalTasks: ["Build CRM integrations", "Connect CRM APIs", "Transform integration data", "Test synchronization workflows"],
    workActivities: ["API integration", "CRM development", "Data synchronization"],
    skills: ["API development", "Programming", "Integration testing"],
    knowledge: ["Application integration"],
    commonTools: ["CRM", "REST APIs", "Salesforce APIs", "Node.js"],
    typicalDeliverables: ["Working integration", "Data mapping", "Integration test report"],
    sourceMappings: [{ source: "internin_curated", externalId: "crm-integration-developer-v1", relation: "exact", sourceVersion: "1" }],
  },
];
